[book]
authors = ["cuihairu"]
language = "en"
multilingual = false
src = "src"
title = "Hello Golang"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]